### ISSUE TITLE
Bump all Remix dependencies 

### ISSUE THREAD

**Issue by brookslybrand** [remix-austin/remixaustin-com#101]
Our remix dependencies are a bit out of date right now

Currently we're on version 1.7.5, and the latest version (at the time of writing this ticket) is 1.15.0

Further, once updating you get a few warnings in the terminal, due to Remix's [future flags](https://remix.run/blog/future-flags).

In the upgrade, it would be good to opt into all of the future flags to disable these warnings, as well as prepare us for v2 🚀 

<img width="853" alt="Rebuilding...
⚠️ REMIX FUTURE CHANGE: The behaviors of `CatchBoundary` and `ErrorBoundary` are changing in v2. You can prepare for this change at your convenience with the `v2_errorBoundary` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#catchboundary-and-errorboundary
⚠️ REMIX FUTURE CHANGE: APIs that provide `formMethod` will be changing in v2. All values will be uppercase (GET, POST, etc.) instead of lowercase (get, post, etc.) You can prepare for this change at your convenience with the `v2_normalizeFormMethod` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#formMethod
⚠️ REMIX FUTURE CHANGE: The route `meta` export signature is changing in v2You can prepare for this change at your convenience with the `v2_meta` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#meta
⚠️ REMIX FUTURE CHANGE: The route file convention is changing in v2. You can prepare for this change at your convenience with the `v2_routeConvention` future flag. For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#file-system-route-convention" src="https://user-images.githubusercontent.com/12396812/234018718-db3db91d-45c6-4d46-aada-b156124fa1c9.png">

**Comment by tcschiller** [comment]
Making some progress locally on getting us to `v1.16.1`. Hope to have a pull request ready soon.

**Comment by brookslybrand** [comment]
> Making some progress locally on getting us to `v1.16.1`. Hope to have a pull request ready soon.

Oh awesome! Excited to see it :)

**Comment by brookslybrand** [comment]
Also @tcschiller see #115 for getting us to v1.15.0. Not sure if it would be helpful to merge that in first or not

**Comment by brookslybrand** [comment]
> Oh excellent @brookslybrand yes let's focus on that first. I'll defer and help out there.

Totally just a first step, doesn't get us all the way. If you're able to get v1.16.1 working, then definitely push up a PR! This was just my attempt to get us a little closer, as well as allow me/others to start turning on the future flags
