### ISSUE TITLE
Cache via Cloudflare appropriately

### ISSUE THREAD

**Issue by grantnorwood** [remix-austin/remixaustin-com#114]
We’re only caching a tiny fraction of the requests to our site at the edge, and we can probably do better 🙂

Do we need to simply pass the [correct cache headers](https://developers.cloudflare.com/cache/about/cache-control/) from our app?

![IMG_1055](https://github.com/remix-austin/remixaustin-com/assets/707463/4081b8a4-472c-4a10-9c45-e5cefc2005dd)

**Comment by matt-hernandez** [comment]
Next up on my list is adding cache headers for the blog page and blog posts.

**Comment by matt-hernandez** [comment]
I merged in #116 which should cache our blog posts. Blog posts less than 4 days old get cached for 8 hours (which seems like a good window to allow for edits). Blog posts at 4 days or older get cached for 1 week. Can we get metrics on whether that is working as expected @grantnorwood?

**Comment by brookslybrand** [comment]
@matt-hernandez I had to set up [a rule](https://medium.com/@akash.now.akash/how-to-setup-cloudflare-cdn-in-a-remix-run-app-website-with-fly-io-f2eff642ee49), but it's working now!

**Before**

https://github.com/remix-austin/remixaustin-com/assets/12396812/d372688c-f731-4835-bbdc-65d4415c1516

**After**

https://github.com/remix-austin/remixaustin-com/assets/12396812/c0bd92e4-b81b-41bd-a261-dd60759efbf0
