### ISSUE TITLE
DX tooling improvements

### ISSUE THREAD

**Issue by tcschiller** [remix-austin/remixaustin-com#18]
Hey team,

I've got a local branch with some DX tooling improvements on it, including:

* Introduce husky, pre-commit quick validate, and some @ts-ignore annotations (to allow typechecking to be re-enabled)
* Add .vscode dir to .gitignore
* Introduce .nvmrc and set to gallium (v16)
* Re-enable typechecking in GitHub workflow

I'd be happy to help contribute here, in whatever small ways I can.

Cheers,

TC

**Comment by brookslybrand** [comment]
Wonderful! Thanks TC

Would love to see this branch if you have time to push up. Thanks for making this issue first 🙏. That's a good reminder to me that I need to go through Grant's contributing doc and add a few opinions.

I'll take a look at any open PRs Monday and gladly provide feedback/approve whatever is open

**Comment by tcschiller** [comment]
Sounds great @brookslybrand. I don't have sufficient permissions to push branches to remote, but once I do, I'll be happy to send this your way!

**Comment by brookslybrand** [comment]
> Sounds great @brookslybrand. I don't have sufficient permissions to push branches to remote, but once I do, I'll be happy to send this your way!

Oh whoops! That's my bad, you should have access now
