### ISSUE TITLE
Select and implement a CMS for page & blog content

### ISSUE THREAD

**Issue by grantnorwood** [remix-austin/remixaustin-com#3]
It would be great to use something that works well with both Remix & React Native ... planning for a mobile app in the future!

Firebase?  Sanity?  Etc?

**Comment by PaulBratslavsky** [comment]
@sethdavis512  Strapi is another good one.  Which can also be self-hosted.  It will be interesting to try a few and see which one fits best.  I may be a bit biased since I love Strapi and work there. 😀

**Comment by brookslybrand** [comment]
> @sethdavis512 Strapi is another good one. Which can also be self-hosted. It will be interesting to try a few and see which one fits best. I may be a bit biased since I love Strapi and work there. 😀 [Strapi](https://strapi.io)

@PaulBratslavsky I'm not crazy familiar, would a free plan be able to support us? Do y'all have any options for community-oriented sites like this one?

Definitely down to try a few options, and would really love to see a version built with strapi

**Comment by grantnorwood** [comment]
I probably made a mistake creating this issue before we knew what we were doing!

But thankfully Brooks created https://github.com/remix-austin/remixaustin-com/discussions/1#discussioncomment-4301017 to discuss this … let’s keep the discussion in this thread instead of the issue I created 🙂

I’ll create a new issue once this is more actionable.
