### ISSUE TITLE
Reduce space on mobile

### ISSUE THREAD

**Issue by brookslybrand** [remix-austin/remixaustin-com#53]
I was browsing the sight in my phone to see how it looked and realized we have an unnecessary amount of white space pushing the main Call To Action button down

Additionally, I think the link in the nav bar should maybe be hidden on mobile, especially since it’s just a link to the home page

![373EF406-7AD3-45CD-8951-33E114C92DC1](https://user-images.githubusercontent.com/12396812/206877626-7361561d-b87d-442a-bdcb-820b50f6b6a2.jpeg)

Looking for thoughts from others or someone to pick this issue up, since it should be pretty straightforward

**Comment by KarenDouglas** [comment]
I can take on this issue.
