### ISSUE TITLE
Meetup CTA needs adjustment on mobile

### ISSUE THREAD

**Issue by sethdavis512** [remix-austin/remixaustin-com#54]
On mobile, the main/hero Meetup CTA gets smooshed.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/3208705/206919511-66fce94f-7a8b-4bcb-981a-e25fa57e28a0.png">

Add padding, line breaks or selectively hide words to make this button look more polished.

**Comment by brookslybrand** [comment]
Oof yeah, definitely a good issue

I'd love to simplify the CTA text, at least on mobile, but don't have strong opinions on what to change it to

**Comment by KarenDouglas** [comment]
I can take this one on!

**Comment by brookslybrand** [comment]
Hey @KarenDouglas, did you handle this in #53?

**Comment by KarenDouglas** [comment]
@brookslybrand  That was for a different issue. I still need to complete this one.

**Comment by brookslybrand** [comment]
Calling bankruptcy on all discussions and issues today. Going to start revamping the direction of this project, so stay tuned 🚀
