### ISSUE TITLE
Shift social links from right side to left side

### ISSUE THREAD

**Issue by sethdavis512** [remix-austin/remixaustin-com#55]
I was tinkering with a few things...thoughts on shifting the logos to the left/top instead of right/bottom?

Current:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/3208705/206920517-32de1e9a-f9c0-407f-b12d-f50e1fa2c903.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/3208705/206920494-d2be532e-aa29-4848-83d6-fd7c99ceec48.png">

<img width="556" alt="image" src="https://user-images.githubusercontent.com/3208705/206920478-686ec5bf-b0ab-4dad-aaf9-9ea7e9c32a05.png">

Adjusted:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/3208705/206920405-9296f3db-4566-4ee3-ac58-a26c80864de0.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/3208705/206920446-c960596c-5b92-4e1e-9a29-84ef7e0fb13f.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/3208705/206920458-aa690eec-feea-4f19-b18c-2b6c4ea4b595.png">

**Comment by brookslybrand** [comment]
Love this, yeah I think that'll look much better 🙂

**Comment by dmorrison** [comment]
Hey, as part of the meetup on Dec 14th, we fixed this one and opened PR #60. Please check it out!
