### ISSUE TITLE
Meetup icon gets cut off

### ISSUE THREAD

**Issue by sethdavis512** [remix-austin/remixaustin-com#56]
Current:
<img width="35" alt="image" src="https://user-images.githubusercontent.com/3208705/206920840-9c2eb348-a069-4af7-b3fc-8a8bbd12bbea.png">

Should be more like this:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/3208705/206921236-a45143ae-b538-42ef-bbc1-febc981e4b5a.png">

**Comment by tripplybrand** [comment]
I'm gonna do it.
