### ISSUE TITLE
Add error monitoring & reporting

### ISSUE THREAD

**Issue by grantnorwood** [remix-austin/remixaustin-com#77]
As a community of developers working as a team, it's important that we have insights into the health of our website.

I suggest adding an error monitoring feature to our site to track & troubleshoot any errors that may arise.

I've already applied for a free OSS license from [Sentry.io](https://sentry.io/for/open-source/), but I'm also interested in suggestions for other approaches.

## PR

I've posted https://github.com/remix-austin/remixaustin-com/pull/79 as my proposal, which is a work-in-progress.

**Comment by brookslybrand** [comment]
Calling bankruptcy on all discussions and issues today. Going to start revamping the direction of this project, so stay tuned 🚀
